name: Docker push and deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: asia-docker.pkg.dev
  IMAGE_NAME: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-private/evm-mcp-server

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Docker build and push in production
        uses: Zilliqa/gh-actions-workflows/actions/ci-dockerized-app-build-push@v2
        with:
          context: .
          push: ${{ github.ref_name == github.event.repository.default_branch }}
          tag: ${{ env.IMAGE_NAME }}
          tag-length: 8
          tag-latest: ${{ github.ref_name == github.event.repository.default_branch }}
          registry: ${{ env.REGISTRY }}
          workload-identity-provider: "${{ secrets.GCP_PRD_GITHUB_WIF }}"
          service-account: "${{ secrets.GCP_PRD_GITHUB_SA_DOCKER_REGISTRY }}"
          cache-key: ${{ env.IMAGE_NAME }}-cache
          build-args: |
            VERSION=${{ github.ref_name }}

  deploy:
    needs: [build]
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    if: github.ref_name == github.event.repository.default_branch
    strategy:
      fail-fast: false
      matrix:
        application:
          - evm-mcp-server
    env:
      APP_NAME: ${{ matrix.application }}
      Z_ENV: z.yaml
      Z_SERVICE_ACCOUNT: ${{ secrets.GCP_PRD_GITHUB_SA_K8S_DEPLOY }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PRD }}
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      Z_IMAGE: asia-docker.pkg.dev/prj-p-devops-services-tvwmrf63/zilliqa-private/z:latest
      REGISTRY: asia-docker.pkg.dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Authenticate to Google Cloud
        id: google-auth
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.GCP_PRD_GITHUB_WIF }}"
          service_account: ${{ env.Z_SERVICE_ACCOUNT }}
          create_credentials_file: true

      - name: Deploy application
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://${{ env.REGISTRY }}
          docker run --rm \
              -e ZQ_USER='${{ env.Z_SERVICE_ACCOUNT }}' \
              -e Z_ENV='/evm-mcp-server/${{ env.Z_ENV }}' \
              -e OP_SERVICE_ACCOUNT_TOKEN='${{ env.OP_SERVICE_ACCOUNT_TOKEN }}' \
              -e GITHUB_PAT='${{ env.GITHUB_PAT }}' \
              -e CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE='/google/application_default_credentials.json' \
              -v `pwd`:/evm-mcp-server \
              -v ${{ steps.google-auth.outputs.credentials_file_path }}:/google/application_default_credentials.json \
              --name z_container ${{ env.Z_IMAGE }} \
              bash -c "gcloud config set account ${{ env.Z_SERVICE_ACCOUNT }} && z /app /evm-mcp-server app sync --cache-dir .cache ${{ env.APP_NAME }}"